import { useEffect, useState } from 'react'
import type { ReactNode, FormEvent } from 'react'
import { createRoot } from 'react-dom/client'
import {
  CommunityScreen,
  ExternalOpportunityDetailScreen,
  OpportunityListingWizard,
  OpportunitiesScreen,
} from './phase8'
import {
  LearningActivityScreen,
  LearningCatalogScreen,
  LearningCourseScreen,
  LearningLessonScreen,
  LearningQuizScreen,
} from './phase9'
import { WalletScreen, WithdrawalScreen } from './phase9-wallet'
import './styles.css'
import './app.css'
import './phase8.css'
import './phase9.css'
import './phase9-flow.css'
import './phase9-wallet.css'
import './tokens.css'
import './responsive-overrides.css'

const API = import.meta.env.VITE_API_URL || '/api'
const assets = { logo:new URL('../icons/stark-h4f.png',import.meta.url).href, spark:new URL('../icons/smart.png',import.meta.url).href, play:new URL('../icons/work.png',import.meta.url).href }
type Route = { path:string; query:URLSearchParams; parts:string[] }
function route(): Route { const url=new URL(location.href); return {path:url.pathname,query:url.searchParams,parts:url.pathname.split('/').filter(Boolean)} }
function go(path:string){const root=document.documentElement;const previousScrollBehavior=root.style.scrollBehavior;root.style.scrollBehavior='auto';history.pushState({},'',path);window.scrollTo(0,0);root.style.scrollBehavior=previousScrollBehavior;window.dispatchEvent(new PopStateEvent('popstate'))}
function BrandLogo({variant='header'}:{variant?:'header'|'auth'}){return <span className={`brand-logo ${variant}-brand-logo`}><img src={assets.logo} alt="Stark"/></span>}
async function api(path:string, options?:RequestInit){ const response=await fetch(`${API}${path}`,{credentials:'include',...options});const payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload.detail||payload.title||`Erro ${response.status}`);(error as Error & {status?:number}).status=response.status;throw error}return payload }
type CurrentSession={pubkey:string;mode:'REAL'|'DEMO';roles?:string[];onboarding_completed?:boolean;expires_at:string}
let sessionRequest:Promise<CurrentSession>|null=null
let sessionExpiresAt=0
function currentSession(){if(sessionRequest&&(!sessionExpiresAt||Date.now()<sessionExpiresAt))return sessionRequest;sessionRequest=api('/me').then(session=>{sessionExpiresAt=Math.max(0,Date.parse(session.expires_at)-1000);return session}).catch(error=>{sessionRequest=null;sessionExpiresAt=0;throw error});return sessionRequest}
export function resetSessionCache(){sessionRequest=null;sessionExpiresAt=0}
const NIP07_TIMEOUT_MS=15_000
function nip07Available(){const signer=(window as any).nostr;return Boolean(signer?.getPublicKey&&signer?.signEvent)}
function withNip07Timeout<T>(operation:Promise<T>):Promise<T>{return new Promise((resolve,reject)=>{const timer=window.setTimeout(()=>reject(new Error('NIP07_TIMEOUT')),NIP07_TIMEOUT_MS);operation.then(value=>{clearTimeout(timer);resolve(value)},error=>{clearTimeout(timer);reject(error)})})}
function nip07ErrorMessage(error:unknown){const message=error instanceof Error?error.message:String(error);if(message==='NIP07_TIMEOUT')return 'A extensão NIP-07 não respondeu. Verifique a permissão e tente novamente.';if(/denied|reject|permission|cancel|negad/i.test(message))return 'A permissão para assinar com NIP-07 foi negada. Nenhuma sessão foi criada.';return 'Não foi possível assinar com a extensão NIP-07. Tente novamente.'}

export function App(){ const [current,setCurrent]=useState(route()); useEffect(()=>{const f=()=>setCurrent(route()); addEventListener('popstate',f); return()=>removeEventListener('popstate',f)},[]); const {path}=current
 if(path==='/') return <Landing/>
 if(path==='/entrar') return <AuthPage/>
 if(path.startsWith('/cadastro')) return <SessionGate returnTo={`${path}${location.search}`}><RegistrationPage step={current.parts[1]||'acesso'}/></SessionGate>
 if(path.startsWith('/app/oportunidades/nova')) return <SessionGate returnTo={`${path}${location.search}`}><AppRoute current={current}/></SessionGate>
 if(path.startsWith('/app')) return <SessionGate returnTo={`${path}${location.search}`}><AppShell><AppRoute current={current}/></AppShell></SessionGate>
 return <NotFound/>
}
function Landing(){return <main className="landing"><nav className="top-nav"><strong>RESILIENCE</strong><button onClick={()=>go('/entrar')}>Empower Now</button></nav><section className="hero"><div className="hero-copy"><div className="spark"><img src={assets.spark} alt=""/></div><h1>Autonomia e<br/><em>Renda para Mulheres</em></h1><p>Diminuímos a distância entre aprender uma habilidade e conquistar uma oportunidade remunerada. Construa seu portfólio, comprove sua experiência e conecte-se a uma rede global com tecnologia Web3.</p><div className="hero-actions"><button className="pink" onClick={()=>go('/entrar')}>Começar Minha Jornada</button><button className="outline" onClick={()=>document.getElementById('bridge')?.scrollIntoView({behavior:'smooth'})}><img src={assets.play} alt=""/>Ver Como Funciona</button></div></div><div className="hero-art"><div className="earning"><span>Capital de liquidez<strong>MOCK</strong></span></div></div></section><section id="bridge" className="bridge"><h2>A Ponte para a <em>Oportunidade</em></h2><p>Conectamos o aprendizado de uma nova habilidade à primeira oportunidade remunerada.</p><div className="cards"><Feature title="Portfólio Real" text="Construa um portfólio tangível através de micro-tarefas e projetos reais."/><Feature title="Experiência Comprovada" text="Cada contribuição é registrada e validada, criando um histórico imutável."/><Feature title="Rede de Contato" text="Conecte-se diretamente com mentoras e oportunidades globais."/></div></section><section className="privacy"><span className="privacy-label">✦ PRIVACIDADE EM PRIMEIRO LUGAR</span><h2>Sua Identidade,<br/>Suas Regras</h2><p>A RESILIENCE utiliza o protocolo Nostr para garantir uma identidade profissional portátil. Nós nunca pedimos suas chaves privadas.</p></section><section className="final-cta"><h2>Pronta para assumir o controle?</h2><p>Junte-se à comunidade de mulheres que estão redefinindo o futuro do trabalho.</p><button className="pink" onClick={()=>go('/entrar')}>Começar Minha Jornada</button></section></main>}
function Feature({title,text}:{title:string;text:string}){return <article className="feature"><div className="feature-icon">✦</div><h3>{title}</h3><p>{text}</p></article>}
function AuthPage(){
 const intent=new URLSearchParams(location.search).get('intent');
 const isSignup=intent==='signup';
 const [error,setError]=useState('');
 const [loading,setLoading]=useState('' as 'nostr'|'demo'|'');
 const [hasNip07,setHasNip07]=useState(nip07Available);
 useEffect(()=>{const detect=()=>setHasNip07(nip07Available());detect();const timer=window.setInterval(detect,250);addEventListener('focus',detect);return()=>{clearInterval(timer);removeEventListener('focus',detect)}},[])
 async function destination(){
  const session=await currentSession();
  if(!session.onboarding_completed)return '/cadastro/acesso';
  const requested=new URLSearchParams(location.search).get('returnTo');
  return requested?.startsWith('/')&&!requested.startsWith('//')?requested:'/app/comunidade';
 }
 async function login(e:FormEvent<HTMLFormElement>){
  e.preventDefault();setError('');setLoading('nostr');
  try{
   const signer=(window as any).nostr;
   if(!signer?.getPublicKey||!signer?.signEvent)throw new Error('A extensão NIP-07 não está disponível neste navegador.');
   const challenge=await api('/auth/nostr/challenges',{method:'POST'});
   let pubkey:string;
   let event:any;
   try{
    pubkey=await withNip07Timeout(Promise.resolve(signer.getPublicKey()));
    event=await withNip07Timeout(Promise.resolve(signer.signEvent({kind:challenge.signing.kind,content:challenge.challenge,tags:[['u',challenge.signing.url],['method',challenge.signing.method],['challenge',challenge.challenge],['payload',challenge.signing.payload_hash]],created_at:Math.floor(Date.now()/1000)})));
   }catch(signerError){throw new Error(nip07ErrorMessage(signerError))}
   if(!event||event.pubkey!==pubkey||typeof event.id!=='string'||typeof event.sig!=='string')throw new Error('A extensão NIP-07 retornou um evento inválido. Nenhuma sessão foi criada.');
   await api('/auth/nostr/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challenge:challenge.challenge,pubkey,signature:event.sig,event})});
   resetSessionCache();go(await destination());
  }catch(err){setError(err instanceof Error?err.message:'Não foi possível entrar.')}finally{setLoading('')}
 }
 async function loginDemo(){
  setError('');setLoading('demo');
  try{await api('/auth/demo/sessions',{method:'POST'});resetSessionCache();go(await destination())}
  catch(err){setError(err instanceof Error?err.message:'Modo demonstração indisponível.')}
  finally{setLoading('')}
 }
 return <main className="auth-page"><form className="auth-card" onSubmit={login}><BrandLogo variant="auth"/><h1>{isSignup?'Criar conta':'Entrar'}</h1><p>Sua identidade é vinculada por uma assinatura Nostr. Sua chave privada nunca é enviada à plataforma.</p>{!hasNip07&&<div className="auth-status" role="status">NIP-07 indisponível. Você pode instalar uma extensão compatível ou continuar no modo demonstração local.</div>}<button className="pink" disabled={Boolean(loading)||!hasNip07} type="submit">{loading==='nostr'?'Conectando...':isSignup?'Continuar com Nostr':'Entrar com Nostr'}</button><button className="outline demo-button" disabled={Boolean(loading)} type="button" onClick={loginDemo}>{loading==='demo'?'Preparando demonstração...':'Continuar em modo demonstração'}</button><small className="demo-note">DEMO — não comprova assinatura Nostr real.</small>{error&&<div className="error" role="alert">{error}</div>}<button type="button" className="link-button" onClick={()=>go(isSignup?'/entrar':'/entrar?intent=signup')}>{isSignup?'Já tenho conta':'Criar conta'}</button></form></main>
}
function RegistrationPage({step}:{step:string}){
 const order=['acesso','identificacao','habilidades','verificacao'];
 const index=Math.max(0,order.indexOf(step));
 const [draft,setDraft]=useState({} as Record<string,any>);
 const [error,setError]=useState('');
 const [loading,setLoading]=useState(true);
 const [saving,setSaving]=useState(false);
 const [preparationAttempt,setPreparationAttempt]=useState(0);
 useEffect(()=>{
  localStorage.removeItem('bluejet_registration');
  setLoading(true);
  setError('');
  api('/onboarding/drafts',{method:'POST'}).then(server=>{setDraft(server);sessionStorage.setItem('bluejet_onboarding_draft',server.id)}).catch(err=>setError(err instanceof Error?err.message:'Não foi possível iniciar o cadastro.')).finally(()=>setLoading(false));
 },[preparationAttempt]);
 function update(key:string,value:any){setDraft(current=>({...current,[key]:value}))}
 function fieldsForStep(){if(step==='acesso')return {name:draft.name,email:draft.email};if(step==='identificacao')return {identity:draft.identity};if(step==='habilidades')return {skills:draft.skills};return {verification:draft.verification,consent:draft.consent}}
 async function next(){
  setError('');
  if(step==='acesso'&&(!draft.name?.trim()||!draft.email?.trim()))return setError('Preencha nome e email.');
  if(step==='identificacao'&&!draft.identity)return setError('Escolha como você se identifica.');
  if(step==='habilidades'&&(!draft.skills||draft.skills.length===0))return setError('Escolha ao menos uma habilidade.');
  if(step==='verificacao'&&!draft.verification)return setError('Escolha uma forma de verificação.');
  if(step==='verificacao'&&!draft.consent)return setError('Aceite os termos para continuar.');
  if(!draft.id)return setError('O cadastro ainda não foi preparado. Tente novamente.');
  setSaving(true);
  try{
   const saved=await api(`/onboarding/drafts/${draft.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(fieldsForStep())});
   setDraft(saved);
   if(index<order.length-1){go(`/cadastro/${order[index+1]}`);return}
   await api(`/onboarding/drafts/${draft.id}/complete`,{method:'POST'});
   sessionStorage.removeItem('bluejet_onboarding_draft');
   resetSessionCache();
   go('/app/comunidade');
  }catch(err){setError(err instanceof Error?err.message:'Não foi possível salvar esta etapa.')}finally{setSaving(false)}
 }
 if(loading)return <main className="auth-page"><p>Preparando cadastro...</p></main>;
 if(error&&!draft.id)return <main className="auth-page"><section className="auth-card"><h1>Não foi possível iniciar o cadastro</h1><div className="error" role="alert">{error}</div><button type="button" className="pink" onClick={()=>setPreparationAttempt(value=>value+1)}>Tentar novamente</button><button type="button" className="link-button" onClick={()=>go('/entrar?intent=signup')}>Voltar</button></section></main>;
 return <main className="auth-page"><form className="auth-card" onSubmit={event=>{event.preventDefault();void next()}}><DemoModeBanner/><span className="step-label">Passo {String(index+1).padStart(2,'0')} de 04</span><h1>{step==='acesso'?'Dados pessoais':step==='identificacao'?'Como você se identifica?':step==='habilidades'?'Suas habilidades':'Verificação'}</h1>{step==='acesso'&&<><label>Nome completo<input autoComplete="name" value={draft.name||''} onChange={e=>update('name',e.target.value)}/></label><label>Email<input type="email" autoComplete="email" value={draft.email||''} onChange={e=>update('email',e.target.value)}/></label><p className="privacy-copy">Sua autenticação continua sendo feita pela assinatura Nostr; não criamos nem armazenamos senha.</p></>}{step==='identificacao'&&<fieldset><legend>Selecione uma opção</legend>{['Mulher','Pessoa não-binária','Prefiro não informar'].map(x=><label className="choice" key={x}><input type="radio" name="identity" checked={draft.identity===x} onChange={()=>update('identity',x)}/>{x}</label>)}</fieldset>}{step==='habilidades'&&<fieldset><legend>Áreas de interesse</legend>{['Tecnologia','Design','Marketing','Data Science','Produto','Gestão'].map(x=><label className="choice" key={x}><input type="checkbox" checked={(draft.skills||[]).includes(x)} onChange={e=>update('skills',e.target.checked?[...(draft.skills||[]),x]:(draft.skills||[]).filter((value:string)=>value!==x))}/>{x}</label>)}</fieldset>}{step==='verificacao'&&<><p>Escolha como deseja iniciar sua verificação.</p><label className="choice"><input type="radio" name="verification" checked={draft.verification==='invite'} onChange={()=>update('verification','invite')}/>Código de convite</label><label className="choice"><input type="radio" name="verification" checked={draft.verification==='manual'} onChange={()=>update('verification','manual')}/>Moderação manual</label><label className="choice"><input type="checkbox" checked={Boolean(draft.consent)} onChange={e=>update('consent',e.target.checked)}/>Aceito os Termos, Privacidade e Regras da Comunidade</label></>}{error&&<div className="error" role="alert">{error}</div>}<button type="submit" className="pink" disabled={saving}>{saving?'Salvando...':index===order.length-1?'Finalizar cadastro':'Continuar'}</button><button type="button" className="link-button" disabled={saving} onClick={()=>go(index?`/cadastro/${order[index-1]}`:'/entrar?intent=signup')}>Voltar</button></form></main>
}
function SessionGate({returnTo,children}:{returnTo:string;children:ReactNode}){const [state,setState]=useState('loading');useEffect(()=>{currentSession().then(session=>{if(returnTo.startsWith('/app')&&session.onboarding_completed===false){setState('redirecting');go('/cadastro/acesso');return}setState('ok')}).catch(error=>{const status=(error as Error & {status?:number}).status;if(status===401){setState('redirecting');const intent=returnTo.startsWith('/cadastro')?'&intent=signup':'';go(`/entrar?returnTo=${encodeURIComponent(returnTo)}${intent}`)}else if(status===403)setState('forbidden');else setState('error')})},[returnTo]);return state==='ok'?<>{children}</>:state==='loading'?<main className="auth-page"><p>Carregando sessão...</p></main>:state==='forbidden'?<Forbidden/>:state==='error'?<main className="auth-page"><section className="auth-card"><h1>Sessão indisponível</h1><p>Não foi possível validar sua sessão. Tente novamente.</p><button className="pink" onClick={()=>{resetSessionCache();location.reload()}}>Tentar novamente</button></section></main>:null}
function DemoModeBanner(){const [demo,setDemo]=useState(false);useEffect(()=>{currentSession().then(session=>setDemo(session.mode==='DEMO')).catch(()=>setDemo(false))},[]);return demo?<div className="demo-banner" role="status">Modo demonstração — identidade Nostr não verificada.</div>:null}
function AppShell({children}:{children:ReactNode}){const [leaving,setLeaving]=useState(false);const [score,setScore]=useState<number|null>(null);useEffect(()=>{api('/wallet/summary').then(value=>setScore(value.score??null)).catch(()=>setScore(null))},[]);async function logout(){setLeaving(true);try{await api('/sessions/current',{method:'DELETE'})}finally{resetSessionCache();go('/entrar')}}return <div className="app-layout"><DemoModeBanner/><header className="app-header"><button className="brand" aria-label="Ir para Comunidade" onClick={()=>go('/app/comunidade')}><BrandLogo/></button><nav aria-label="Navegação principal"><button aria-current={location.pathname.startsWith('/app/oportunidades')?'page':undefined} onClick={()=>go('/app/oportunidades')}>Oportunidades</button><button aria-current={location.pathname==='/app/comunidade'?'page':undefined} onClick={()=>go('/app/comunidade')}>Comunidade</button><button aria-current={location.pathname.startsWith('/app/capacitacao')?'page':undefined} onClick={()=>go('/app/capacitacao')}>Capacitação</button></nav><span className="header-score" aria-label={score===null?'Score indisponível':`Score ${score}`}>{score??'—'} Z</span><button className="link-button logout-button" disabled={leaving} onClick={logout}>{leaving?'Saindo...':'Sair'}</button><button className="avatar" aria-label="Abrir minha carteira" onClick={()=>go('/app/carteira')}>U</button></header>{children}</div>}
function AppRoute({current}:{current:Route}){const p=current.path;if(p==='/app/comunidade')return <Community/>;if(p==='/app/oportunidades')return <Opportunities query={current.query}/>;if(p.startsWith('/app/oportunidades/nova'))return <OpportunityWizard step={current.parts[3]||'basico'}/>;if(p.match(/^\/app\/oportunidades\/externas\/[^/]+$/))return <ExternalOpportunityDetail id={current.parts[3]}/>;if(p.match(/^\/app\/oportunidades\/[^/]+\/candidatura$/))return <Application id={current.parts[2]}/>;if(p.match(/^\/app\/oportunidades\/[^/]+$/))return <OpportunityDetail id={current.parts[2]}/>;if(p==='/app/capacitacao')return <Learning/>;if(p.match(/^\/app\/capacitacao\/[^/]+\/quiz$/))return <Quiz courseId={current.parts[2]}/>;if(p.match(/^\/app\/capacitacao\/[^/]+\/aulas\/[^/]+$/))return <Lesson courseId={current.parts[2]} lessonId={current.parts[4]}/>;if(p.match(/^\/app\/capacitacao\/[^/]+\/atividades\/[^/]+$/))return <Activity courseId={current.parts[2]} activityId={current.parts[4]}/>;if(p.match(/^\/app\/capacitacao\/[^/]+$/))return <Course id={current.parts[2]} activitySubmitted={current.query.get('atividade')==='enviada'}/>;if(p==='/app/carteira/saque')return <Withdrawal/>;if(p==='/app/carteira')return <Wallet/>;if(p==='/app/revisao')return <ReviewQueue/>;if(p.match(/^\/app\/pagamentos\/[^/]+$/))return <Payment assignmentId={current.parts[2]}/>;if(p.match(/^\/app\/recibos\/[^/]+$/))return <Receipt id={current.parts[2]}/>;if(p.match(/^\/app\/trabalhos\//))return <Work id={current.parts[2]}/>;return <NotFound/>}
function Community(){return <CommunityScreen api={api} navigate={go}/>}
function Opportunities({query}:{query:URLSearchParams}){return <OpportunitiesScreen api={api} navigate={go} query={query}/>}
function ExternalOpportunityDetail({id}:{id:string}){return <ExternalOpportunityDetailScreen api={api} navigate={go} id={id}/>}
function OpportunityDetail({id}:{id:string}){const [state,setState]=useState<any>({loading:true});const [reserving,setReserving]=useState(false);const [error,setError]=useState('');useEffect(()=>{api(`/paid-tasks/${id}`).then(data=>setState({data})).catch(e=>setState({error:String(e.message)==='404'?'notFound':'error'}))},[id]);async function reserve(){setReserving(true);setError('');try{const assignment=await api(`/paid-tasks/${id}/assignment-reservations`,{method:'POST'});go(`/app/oportunidades/${id}/candidatura?assignmentId=${encodeURIComponent(assignment.id)}`)}catch(e){setError(e instanceof Error&&e.message==='409'?'Esta tarefa já está reservada ou indisponível.':'Não foi possível reservar a tarefa.')}finally{setReserving(false)}}if(state.loading)return <Page title="Carregando..."><div className="empty">Carregando oportunidade...</div></Page>;if(state.error)return <Page title={state.error==='notFound'?'Oportunidade não encontrada':'Erro'}><ErrorState retry={()=>location.reload()}/></Page>;const t=state.data;return <Page title={t.title}><div className="panel"><span className="eyebrow">{t.company?.name||'Organização'} · PAID_TASK</span><p>{t.instructions}</p><strong>{t.reward_sats} sats</strong><p>Ao continuar, a vaga será reservada por 60 minutos.</p><button className="pink" disabled={reserving} onClick={reserve}>{reserving?'Reservando...':'Reservar e candidatar-se'}</button>{error&&<div className="error" role="alert">{error}</div>}</div></Page>}
function Learning(){return <LearningCatalogScreen api={api} navigate={go}/>}
function Course({id,activitySubmitted}:{id:string;activitySubmitted:boolean}){return <LearningCourseScreen api={api} navigate={go} courseId={id} activitySubmitted={activitySubmitted}/>}
function Lesson({courseId,lessonId}:{courseId:string;lessonId:string}){return <LearningLessonScreen api={api} navigate={go} courseId={courseId} lessonId={lessonId}/>}
function Activity({courseId,activityId}:{courseId:string;activityId:string}){return <LearningActivityScreen api={api} navigate={go} courseId={courseId} activityId={activityId}/>}
function OpportunityWizard({step}:{step:string}){return <OpportunityListingWizard api={api} navigate={go} step={step}/>}
function Application({id}:{id:string}){const [message,setMessage]=useState('');const [state,setState]=useState('idle');const assignmentId=new URLSearchParams(location.search).get('assignmentId')||undefined;async function submit(){setState('saving');try{const application=await api(`/paid-tasks/${id}/applications`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,assignment_id:assignmentId})});const activityAssignmentId=application.assignment_id||assignmentId;if(activityAssignmentId)return go(`/app/trabalhos/${encodeURIComponent(activityAssignmentId)}/entrega`);setState('sent')}catch(e){setState(e instanceof Error&&e.message==='409'?'duplicate':'error')}}return <Page title="Candidatura"><div className="panel"><p>Oportunidade {id}</p>{assignmentId&&<p className="eyebrow">Reserva vinculada: {assignmentId}</p>}<label htmlFor="application-message">Mensagem de candidatura<textarea id="application-message" value={message} onChange={e=>setMessage(e.target.value)}/></label><button className="pink" disabled={state==='saving'} onClick={submit}>{state==='saving'?'Enviando...':state==='sent'?'Candidatura enviada':'Enviar candidatura'}</button>{state==='duplicate'&&<div className="error" role="alert">Você já se candidatou a esta oportunidade.</div>}{state==='error'&&<ErrorState retry={()=>setState('idle')}/>}</div></Page>}
function Wallet(){return <WalletScreen api={api} navigate={go}/>}
function Withdrawal(){return <WithdrawalScreen api={api} navigate={go}/>}
function Work({id}:{id:string}){const [content,setContent]=useState('');const [file,setFile]=useState<any>();const [status,setStatus]=useState('idle');const [state,setState]=useState<any>({loading:true});useEffect(()=>{api(`/assignments/${id}`).then(data=>setState({data})).catch(e=>setState({error:e.message}))},[id]);async function saveDraft(){setStatus('saving');try{await api(`/assignments/${id}/submissions/draft`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,filename:file?.name||'submission.txt',mime_type:file?.type||'text/plain'})});setStatus('draft')}catch{setStatus('error')}}async function submit(){setStatus('saving');try{let uploadId:string|undefined;if(file){const upload=await api('/uploads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,mime_type:file.type,size:file.size})});uploadId=upload.upload_id}await api(`/assignments/${id}/submissions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,filename:file?.name||'submission.txt',mime_type:file?.type||'application/pdf',upload_id:uploadId})});setStatus('submitted')}catch{setStatus('error')}}if(state.loading)return <Page title="Entrega profissional"><Empty text="Carregando trabalho..."/></Page>;if(state.error)return <Page title="Entrega profissional"><ErrorState retry={()=>location.reload()} message={state.error==='403'?'Você não tem acesso a este trabalho.':state.error==='404'?'Trabalho não encontrado.':undefined}/></Page>;return <Page title="Entrega profissional"><div className="panel"><span className="eyebrow">Assignment {id}</span><h2>{state.data.task?.title||'Trabalho atribuído'}</h2><p>{state.data.task?.instructions}</p><label htmlFor="submission-content">Descrição da entrega<textarea id="submission-content" value={content} onChange={e=>setContent(e.target.value)}/></label><label htmlFor="submission-file">Anexo profissional<input id="submission-file" type="file" accept="image/png,image/jpeg,application/pdf,video/mp4" onChange={e=>setFile(e.target.files?.[0])}/></label>{file&&<p>{file.name} · {Math.round(file.size/1024)} KB</p>}<button className="link-button" disabled={!content||status==='saving'} onClick={saveDraft}>{status==='draft'?'Rascunho salvo':'Salvar rascunho'}</button><button className="pink" disabled={!content||status==='saving'} onClick={submit}>{status==='saving'?'Enviando...':status==='submitted'?'Enviada':'Enviar entrega'}</button>{status==='submitted'&&<button className="link-button" onClick={()=>go(`/app/pagamentos/${id}`)}>Acompanhar revisão e pagamento</button>}{status==='error'&&<div className="error" role="alert">Não foi possível enviar a entrega ou o anexo.</div>}</div></Page>}
function Quiz({courseId}:{courseId:string}){return <LearningQuizScreen api={api} navigate={go} courseId={courseId}/>}
function ReviewQueue(){const [state,setState]=useState<any>({loading:true});const [reason,setReason]=useState({});const [error,setError]=useState('');async function load(){setState({loading:true});try{const data=await api('/admin/review-queue');setState({items:data.items||[]})}catch(e){setState({error:e instanceof Error?e.message:'network'})}}useEffect(()=>{load()},[]);async function decide(id:string,decision:string){if((decision==='REQUEST_CHANGES'||decision==='REJECT')&&!reason[id]?.trim()){setError('Correção ou rejeição exige justificativa.');return}setError('');try{await api(`/admin/submissions/${id}/reviews`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision,reason:reason[id]||''})});await load()}catch{setError('Não foi possível registrar a revisão.')}}if(state.loading)return <Page title="Revisão"><Empty text="Carregando fila de revisão..."/></Page>;if(state.error)return <Page title="Revisão"><ErrorState retry={load}/></Page>;return <Page title="Revisão humana"><p>Somente aprovação humana cria obrigação financeira.</p>{error&&<div className="error" role="alert">{error}</div>}{state.items.length?state.items.map((item:any)=><article className="panel" key={item.id}><span className="eyebrow">Submission {item.id}</span><p>Assignment: {item.assignment_id}</p><label htmlFor={`review-${item.id}`}>Justificativa<textarea id={`review-${item.id}`} value={reason[item.id]||''} onChange={e=>setReason((v:any)=>({...v,[item.id]:e.target.value}))}/></label><button className="pink" onClick={()=>decide(item.id,'APPROVE')}>Aprovar e criar obrigação</button><button className="link-button" onClick={()=>decide(item.id,'REQUEST_CHANGES')}>Solicitar correção</button><button className="link-button" onClick={()=>decide(item.id,'REJECT')}>Rejeitar</button></article>):<Empty text="Nenhuma entrega pendente de revisão."/>}</Page>}
function Payment({assignmentId}:{assignmentId:string}){const [state,setState]=useState<any>({loading:true});const [invoice,setInvoice]=useState('');const [attempt,setAttempt]=useState<any>(null);const [error,setError]=useState('');useEffect(()=>{api(`/assignments/${assignmentId}/payment-obligation`).then(data=>setState({data})).catch(e=>setState({error:e.message}))},[assignmentId]);async function pay(){if(!invoice.trim())return setError('Informe uma invoice BOLT11.');setError('');try{const data=await api(`/payment-obligations/${state.data.id}/payout-attempts`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':`web-${assignmentId}`},body:JSON.stringify({invoice:invoice.trim()})});setAttempt(data)}catch(e){setError(e instanceof Error&&e.message==='409'?'Já existe uma tentativa ativa para esta obrigação.':'Não foi possível iniciar o pagamento.')}}async function refresh(){if(!state.data)return;try{const data=await api(`/payment-obligations/${state.data.id}/payout-status`);setAttempt(data.attempt);if(data.attempt?.status==='SETTLED')setError('Pagamento liquidado. Consulte o recibo quando disponível.')}catch{setError('Não foi possível atualizar o estado do pagamento.')}}if(state.loading)return <Page title="Pagamento"><Empty text="Carregando obrigação..."/></Page>;if(state.error)return <Page title="Pagamento"><ErrorState retry={()=>location.reload()}/></Page>;return <Page title="Pagamento Lightning"><div className="panel"><span className="eyebrow">Modo: {attempt?.mode||'MOCK'}</span><p>Valor aprovado: <strong>{state.data.amount_sats} sats</strong></p><label htmlFor="bolt11-invoice">Invoice BOLT11<input id="bolt11-invoice" value={invoice} onChange={e=>setInvoice(e.target.value)} placeholder="Cole a invoice da sua carteira"/></label>{error&&<div className="error" role="alert">{error}</div>}{!attempt?<button className="pink" onClick={pay}>Enviar para pagamento</button>:<><p>Estado: {attempt.status}</p><button className="pink" onClick={refresh}>Atualizar estado</button></>}</div></Page>}
function Receipt({id}:{id:string}){const [state,setState]=useState<any>({loading:true});useEffect(()=>{api(`/receipts/${id}`).then(data=>setState({data})).catch(e=>setState({error:e.message}))},[id]);if(state.loading)return <Page title="Recibo"><Empty text="Carregando recibo..."/></Page>;if(state.error)return <Page title="Recibo"><ErrorState retry={()=>location.reload()}/></Page>;return <Page title="Recibo de pagamento"><div className="panel"><span className="eyebrow">Pagamento liquidado · {state.data.mode}</span><h2>{state.data.amount_sats} sats</h2><p>Identificador do recibo: {state.data.id}</p><p>Impacto realizado: este valor vem de um pagamento liquidado, não de simulação.</p></div></Page>}
function Page({title,children}:{title:string;children:ReactNode}){return <main className="page"><h1>{title}</h1>{children}</main>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function ErrorState({retry,message='Não foi possível carregar os dados.'}:{retry:()=>void;message?:string}){return <div className="empty error" role="alert">{message} <button className="link-button" onClick={retry}>Tentar novamente</button></div>}
function NotFound(){return <main className="auth-page"><section className="auth-card"><h1>404</h1><p>Página não encontrada.</p><button className="pink" onClick={()=>go('/')}>Voltar</button></section></main>}
function Forbidden(){return <main className="auth-page"><section className="auth-card"><h1>403</h1><p>Você não tem permissão para acessar este conteúdo.</p><button className="pink" onClick={()=>go('/app/comunidade')}>Voltar ao aplicativo</button></section></main>}
const appRoot=document.getElementById('root');
const bluejetGlobal=globalThis as typeof globalThis&{__bluejetReactRoot?:ReturnType<typeof createRoot>};
if(appRoot){const reactRoot=bluejetGlobal.__bluejetReactRoot??createRoot(appRoot);bluejetGlobal.__bluejetReactRoot=reactRoot;reactRoot.render(<App/>)}
